### ISSUE TITLE
Призрак отображается в воздухе, тогда как постройка прижата к земле

### ISSUE THREAD

**Issue by Zaubererbruder** [Zaubererbruder/ConveyorProject#10]
![image](https://user-images.githubusercontent.com/46814610/183473389-c872707d-b5f7-446d-9fb9-9d70ddb6a99b.png)
Нужно мнение Витали, о том каким должен быть конвейер. Если в воздухе, то я просто поправлю префаб. Если прижат к земле, то не просто поправлю префаб

**Comment by Nextovoy** [comment]
"Призрак" должен быть прижат к земле. Все необходимые изменения в модель были внесены.
